### ISSUE TITLE
i dont find sourcepawn.jit.x86.so 

### ISSUE THREAD

**Issue by gost442** [spumer/ProtectSMX#4]
i build sourcemod in linux and do all steps and all good but i dont find  this parte ... After that you will have sourcepawn.jit.x86.so which will encrypt all .smx files. You can use only it or whole self-compiled SM

**Comment by spumer** [comment]
How you search it?

**Comment by gost442** [comment]
In vps filezilla in build folder

**Comment by gost442** [comment]
I build sourcemod 1.10 with protect smx but dont find that

**Comment by spumer** [comment]
You can find it here: "./package/addons/sourcemod/bin/sourcepawn.jit.x86.so"

See build log:
https://github.com/alliedmodders/sourcemod/runs/5770166049?check_suite_focus=true#step:9:1724

**Comment by gost442** [comment]
oki i find that now, in linux how i use that to compile .sp now? i need create new folder or something like that?

**Comment by spumer** [comment]
Please read the readme again

**Comment by gost442** [comment]
After that you will have sourcepawn.jit.x86.so which will encrypt all .smx files. You can use only it or whole self-compiled SM. But how i do this ? How i compile with only sourcepawn.jitx86.so
